[package]

name = "eventfd"
version = "0.1.1"
authors = ["Jeremy Fitzhardinge <jeremy@goop.org>"]
description = "Binding to Linux's eventfd syscall"
repository = "https://github.com/jsgf/eventfd-rust.git"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
nix = "0.14"
